# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dane Balia
email: textusreceptus@tuta.io
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal site, an expression of my learning, wisdom gained, experience and opinion.
baseurl: "" # the subpath of your site, e.g. /blog
domain: danebalia.com
url: "https://www.danebalia.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: daneb
logo: images/avatar.png

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" 

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


destination: docs/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include: ["_pages"]

keep_files: ['CNAME']
  
# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  poetry:
    output: true
    permalink: /:collection/:path/
  sermons:
    output: true
    permalink: /:collection/:path/
  software:
    output: true
    permalink: /:collection/:path/
  video:
    output: true
    permalink: /:collection/:path/
  
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: true
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # poetry
  - scope:
      path: ""
      type: poetry
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # sermons
  - scope:
      path: ""
      type: sermons
    values:
      layout: single
      author_profile: true
      share: true
      read_time: true
      comment: true
  # software 
  - scope:
      path: ""
      type: software 
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comment: true
  # videos
  - scope:
      path: ""
      type: video
    values:
      layout: single
      author_profile: true
      share: true
      comment: false



